name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        # Asennetaan vain Buildozerin vaatimat peruskääntäjät
        sudo apt-get install -y libtool automake autoconf gettext python3-pip openjdk-17-jdk unzip
        pip install --upgrade pip
        pip install buildozer cython==0.29.33

    - name: Build with Buildozer
      run: |
        # yes-komento putkitetaan buildozerille, jotta se hyväksyy automaattisesti 
        # kaikki sen itsensä lataamat Android SDK -lisenssit prosessin aikana.
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: moode-audio-apk
        path: bin/*.apk
